### PR TITLE
Updated installation.html

### PR DESCRIPTION
**Pull request by flohorovicic**
# Description

Only updates in documentation:
* installation.html: added info for gempy-viewer

Relates to [#955](https://github.com/gempy-project/gempy/issues/955) Closes [#955](https://github.com/gempy-project/gempy/issues/955)

### CODE REVIEW

**Comment by Leguark** [comment]
That worked! Thanks. Have you generated the example for the videos too?

**Comment by flohorovicic** [comment]
Coming up - just wanted to check first how the documentation update works :-) So: coming soon!

Another quick question: where to upload the changed .rst-file? To the main branch? Or also to gh-pages?

**Comment by flohorovicic** [comment]
Thanks for the quick answer! Ok, so then I'll add the .rst to the main branch (in the next pull request, together with some more changes :-) ).

Here, a summary of the process, to make sure we get this correct (and for future reference):

To update documentation and website:
1) Fork entire repo repo (note: ensure that not only _main_ is forked, as standard GitHub setting, but the entire repo, including the _gh_pages_ branch).
2) Clone repo, create documentation locally with `sphinx` from _main_-branch
3) Update .rst files as required (and/ or add new examples, update gallery, etc.)
4) Add generated .html-files to branch _gh_main_
5) Push changes and create pull request for both branches.

Hope I got this correct :-)

**Comment by flohorovicic** [comment]
For future reference: check description here (without fork, but else the same):

https://github.com/gempy-project/gempy/blob/main/DevelopersGuide.md#to-push-the-docs-in-a-fancy-way

**Pull request merged**
