### PR TITLE
[WIP] Documentation and robustification of Kriging for spacial interpolation

### PR DESCRIPTION
**Pull request by TobiasGlaubach**
# Description
1.) Added documentation in docstrings
2.) replaced prints  for errors with actual exceptions
3.) implemented a scheme where the equation system can be solved either by QR decomposition or least square minimzation or 'smart' by calculating the rank first. Implemented a default parameter so that the original impleentation is conserved.

# Checklist
- [x] My code follows the [PEP 8 style guidelines](https://www.python.org/dev/peps/pep-0008/).
- [x] My code uses type hinting for function and method arguments and return values.
- [x] My code contains descriptive and helpful docstrings 
which are formatted per the [Google Python Style Guidelines] (http://google.github.io/styleguide/pyguide.html). --> used standard Pycharm doc string format
- [ ] I have created tests which entirely cover my code.
- [ ] The test code either 1. demonstrates at least one valuable use case (e.g. integration tests) 
or 2. verifies that outputs are as expected for given inputs (e.g. unit tests).
- [ ] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by javoha** [comment]
Hello @TobiasGlaubach ,

thanks a lot for this - I wrote this during my first coding steps and it needed this polishing (and probably needs some more). I will take this pull request as a chance to write some tests to cover the code - jsut so you don't wonder that it takes a while.

Thanks again, best wishes and stay healthy!

**Comment by Leguark** [comment]
Can you merge this branch with master to fix travis

**Comment by pytzcarraldo** [comment]
I've tagged the PR as a WIP as long as this is being worked on. Let me know when / if you need review!  🤙

**Comment by Leguark** [comment]
This is pending adding tests or am I mistaken @javoha ? (no rush though)

**Comment by javoha** [comment]
> This is pending adding tests or am I mistaken @javoha ? (no rush though)

Yes, might take me a bit though with the semester starting.

**Comment by Leguark** [comment]
hopefully, we will come back to this soon but for now we close it

**Pull request closed without merging**
